Result.create(player:'A')
Result.create(player:'B')
Result.create(player:'C')
Result.create(player:'D')
Result.create(player:'E')
Result.create(player:'F')
Result.create(player:'G')
Result.create(player:'H')
Result.create(player:'I')
Result.create(player:'J')

# Result.create(cell:'1_2')
# Result.create(cell:'1_3')
# Result.create(cell:'1_4')
# Result.create(cell:'1_5')
# Result.create(cell:'1_6')
# Result.create(cell:'1_7')
# Result.create(cell:'1_8')
# Result.create(cell:'1_9')
# Result.create(cell:'1_10')
# Result.create(cell:'2_1')
# Result.create(cell:'2_3')
# Result.create(cell:'2_4')
# Result.create(cell:'2_5')
# Result.create(cell:'2_6')
# Result.create(cell:'2_7')
# Result.create(cell:'2_8')
# Result.create(cell:'2_9')
# Result.create(cell:'2_10')
# Result.create(cell:'3_1')
# Result.create(cell:'3_2')
# Result.create(cell:'3_4')
# Result.create(cell:'3_5')
# Result.create(cell:'3_6')
# Result.create(cell:'3_7')
# Result.create(cell:'3_8')
# Result.create(cell:'3_9')
# Result.create(cell:'3_10')
# Result.create(cell:'4_1')
# Result.create(cell:'4_2')
# Result.create(cell:'4_3')
# Result.create(cell:'4_5')
# Result.create(cell:'4_6')
# Result.create(cell:'4_7')
# Result.create(cell:'4_8')
# Result.create(cell:'4_9')
# Result.create(cell:'4_10')
# Result.create(cell:'5_1')
# Result.create(cell:'5_2')
# Result.create(cell:'5_3')
# Result.create(cell:'5_4')
# Result.create(cell:'5_6')
# Result.create(cell:'5_7')
# Result.create(cell:'5_8')
# Result.create(cell:'5_9')
# Result.create(cell:'5_10')
# Result.create(cell:'6_1')
# Result.create(cell:'6_2')
# Result.create(cell:'6_3')
# Result.create(cell:'6_4')
# Result.create(cell:'6_5')
# Result.create(cell:'6_7')
# Result.create(cell:'6_8')
# Result.create(cell:'6_9')
# Result.create(cell:'6_10')
# Result.create(cell:'7_1')
# Result.create(cell:'7_2')
# Result.create(cell:'7_3')
# Result.create(cell:'7_4')
# Result.create(cell:'7_5')
# Result.create(cell:'7_6')
# Result.create(cell:'7_8')
# Result.create(cell:'7_9')
# Result.create(cell:'7_10')
# Result.create(cell:'8_1')
# Result.create(cell:'8_2')
# Result.create(cell:'8_3')
# Result.create(cell:'8_4')
# Result.create(cell:'8_5')
# Result.create(cell:'8_6')
# Result.create(cell:'8_7')
# Result.create(cell:'8_9')
# Result.create(cell:'8_10')
# Result.create(cell:'9_1')
# Result.create(cell:'9_2')
# Result.create(cell:'9_3')
# Result.create(cell:'9_4')
# Result.create(cell:'9_5')
# Result.create(cell:'9_6')
# Result.create(cell:'9_7')
# Result.create(cell:'9_8')
# Result.create(cell:'9_10')
# Result.create(cell:'10_1')
# Result.create(cell:'10_2')
# Result.create(cell:'10_3')
# Result.create(cell:'10_4')
# Result.create(cell:'10_5')
# Result.create(cell:'10_6')
# Result.create(cell:'10_7')
# Result.create(cell:'10_8')
# Result.create(cell:'10_9')